name: Sync and Deploy Assets

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'What do you want to sync?'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - laser

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - id: set-matrix
        name: Generate Matrix Configuration
        run: |
          CHOICE="${{ github.event.inputs.service }}"
          if [ "$CHOICE" = "all" ]; then
            SERVICES_JSON=$(find . -maxdepth 1 -type d ! -name ".*" ! -name "." ! -name "nost-connect" | sed 's|^\./||' | jq -R . | jq -s -c .)
            echo "matrix=$SERVICES_JSON" >> $GITHUB_OUTPUT
          else
            echo "matrix=[\"$CHOICE\"]" >> $GITHUB_OUTPUT
          fi

  process-assets:
    name: Sync ${{ matrix.service }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Process assets for ${{ matrix.service }}
        run: cd "${{ matrix.service }}" && chmod +x ./sync.sh && ./sync.sh

      - name: Upload processed service assets
        uses: actions/upload-artifact@v7
        with:
          name: assets-${{ matrix.service }}
          path: ${{ matrix.service }}/

  deploy:
    name: Deploy to GitHub Pages
    needs: process-assets
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download all processed assets
        uses: actions/download-artifact@v8
        with:
          pattern: assets-*
          path: .github/temp-assets

      - name: Merge assets back to directories
        run: |
          cd .github/temp-assets
          tree
          for dir in assets-*; do
            if [ -d "$dir" ]; then
              svc_name=${dir#assets-}
              rm -rf "../../$svc_name"
              mkdir -p "../../$svc_name"
              cp -r "$dir"/. "../../$svc_name/"
            fi
          done
          cd ../..
          rm -rf .github/temp-assets

      - name: Disable Jekyll processing
        run: touch .nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
